-- USERS ARE HERE
INSERT INTO user (username, email) VALUES("HasTheGuyDoWalk", "Emperor@inbox.net")
INSERT INTO user (username, email) VALUES("HasBotGuyHasBot", "Backend@yahoo.com")
INSERT INTO user (username, email) VALUES("IsFeelGuyIsFeel", "Nobody@sendreceive.net")
INSERT INTO user (username, email) VALUES("IsGetBackend", "GuyDoesSwim@fastmail.org")
INSERT INTO user (username, email) VALUES("IsRandomSomeSomebody", "King@fastmail.org")
INSERT INTO user (username, email) VALUES("LikesAnonymousSnailcat", "Database@sendreceive.mail")
INSERT INTO user (username, email) VALUES("IsGoDatabase", "Somebody@yahoo.net")
INSERT INTO user (username, email) VALUES("LookingCoolAnonymous", "PeopleAreGuyLookingRobusts@yahoo.com")
INSERT INTO user (username, email) VALUES("IsGalIsRamielDatabase", "Not-a-GuyIsAnonymous@fastmail.org")
INSERT INTO user (username, email) VALUES("HasGuyIsFeelingEmperor", "SomeLuduk@gmail.mail")

-- TAGS ARE HERE
INSERT INTO tag (name, colour, background, priority) VALUES("CoolGuyHasCoffeefor", "#555555", "#dddddd", 2)
INSERT INTO tag (name, colour, background, priority) VALUES("HasSomeFrontend", "#ffffff", "#555555", 1)
INSERT INTO tag (name, colour, background, priority) VALUES("IsTheGuy", "#dddddd", "#444444", 6)
INSERT INTO tag (name, colour, background, priority) VALUES("LikesTotallyLuduk", "#999999", "#aaaaaa", 0)
INSERT INTO tag (name, colour, background, priority) VALUES("", "#ffffff", "#ffffff", 8)
INSERT INTO tag (name, colour, background, priority) VALUES("IsWalk", "#bbbbbb", "#cccccc", 10)
INSERT INTO tag (name, colour, background, priority) VALUES("LookingBlack", "#444444", "#ffffff", 2)
INSERT INTO tag (name, colour, background, priority) VALUES("IsSomeNobody", "#ffffff", "#ffffff", 7)
INSERT INTO tag (name, colour, background, priority) VALUES("CanFeel", "#888888", "#777777", 10)
INSERT INTO tag (name, colour, background, priority) VALUES("HasTheGuy", "#aaaaaa", "#bbbbbb", 6)
INSERT INTO tag (name, colour, background, priority) VALUES("IsRun", "#dddddd", "#eeeeee", 2)
INSERT INTO tag (name, colour, background, priority) VALUES("HasSoftware", "#ffffff", "#dddddd", 4)
INSERT INTO tag (name, colour, background, priority) VALUES("OrangeGuyHasFrontendfor", "#222222", "#eeeeee", 6)
INSERT INTO tag (name, colour, background, priority) VALUES("IsCoffee", "#bbbbbb", "#555555", 5)
INSERT INTO tag (name, colour, background, priority) VALUES("CanEnjoy", "#999999", "#000000", 8)

-- NOTES ARE HERE
INSERT INTO note (content, created) VALUES("Luduk LikesDatabase Luduk  Ramiel Gray Walk! Not-a-Guy HasGuy Not-a-Guy Get Enjoyable, White Backend IsSwim Readable? Nobody Random Walk?", 1577091821)
INSERT INTO note (content, created) VALUES("Orange King IsNot-a-Snailcat Random. Green DoGet HasSoftware Real, Anonymous LookingReal Anonymous Feel Real. Yellow Ramiel LookingEnjoyable Enjoyable.", 1576705154)
INSERT INTO note (content, created) VALUES("TotallyRamiel Real Enjoy! Snailcat IsUnreal Snailcat Get Unreal, King Cool Go; Person IsAnonymous Person Get Feeling! Red Software LookingEnjoyable Enjoyable?", 1576377843)
INSERT INTO note (content, created) VALUES("Orange Ramiel LikesSnailcat Rational. PeopleAreDoGos Feeling Enjoy  Nobody YellowGuyLookingRandomfor Nobody Get Yellow. Person  Person!", 1576393815)
INSERT INTO note (content, created) VALUES("Green Bot IsFrontend Readable, Luduk CanGet Luduk, Database IsCool Database! Gray Not-a-Ramiel IsEnjoyable Enjoyable! GalHasGuy HasGuy GalHasGuy!", 1576330661)
INSERT INTO note (content, created) VALUES("Snailcat IsEnjoyable Snailcat. Black TotallyGalDoesGo LookingCool Cool! GuyCanWalk CanWalk GuyCanWalk Walk Responsible; Bot IsHave Bot.", 1576501482)
INSERT INTO note (content, created) VALUES("Ramiel IsSwim Ramiel Swim Responsible, GalCanHave CanHave GalCanHave Have Gray, Violet Nobody LikesPerson Unreal, Yellow Ramiel ResponsibleGuyCanRunfor Responsible.", 1577007753)
INSERT INTO note (content, created) VALUES("Ramiel IsRun Ramiel. DoHave ResponsibleEmperorfor DoHave, Frontend LookingRandom Frontend Enjoy Random? Coffee HasNot-a-Backend Coffee!", 1576176067)
INSERT INTO note (content, created) VALUES("Nobody CanGet Nobody Get Rational! Database LookingCool Database  Design Irrational Walk? Violet Database IrrationalNot-a-Kingfor Irrational  Design UnrealDoEnjoyfor Design.", 1576143461)
INSERT INTO note (content, created) VALUES("Nobody IsGet Nobody Get Cool; GuyHasSomeDesign HasSomeDesign GuyHasSomeDesign; Anonymous Random Have; Nobody RandomGuyLikesSomeNot-a-Somebodyfor Nobody Walk Random.", 1576485586)
INSERT INTO note (content, created) VALUES("Emperor Cool Enjoy; TotallySoftware IsSoftware TotallySoftware. Bot LookingCyan Bot Walk Cyan  White Software IrrationalAnonymousfor Irrational. Gray Anonymous LookingCool Cool!", 1577038228)
INSERT INTO note (content, created) VALUES("Black Ramiel IsWalk Robust, Cyan Design HasGalIsDesign Real  Emperor  Emperor Have Black? PeopleAreSnailcats CanFeel PeopleAreSnailcats. Cyan Coffee DoesSwim Subprime!", 1576691738)
INSERT INTO note (content, created) VALUES("TheGuy Unreal Swim! DoFeel DoesFeel DoFeel Feel Unreal  PeopleAreDoSwims Robust Run! PeopleAreSomeDesigns RealSomeDesignfor PeopleAreSomeDesigns Enjoy Real  TotallyRamiel Rational Walk?", 1576717265)
INSERT INTO note (content, created) VALUES("Software  Software Feel Robust; Green King FeelingNobodyfor Feeling! Not-a-TheGuy  Not-a-TheGuy! PeopleAreTheGuys IsTheGuy PeopleAreTheGuys? Green Ramiel CanGet Irrational?", 1577077810)
INSERT INTO note (content, created) VALUES("PeopleAreTheGuys IsHave PeopleAreTheGuys Have Feeling; Ramiel Cool Enjoy? GalLookingRandom Random Have! Anonymous IsResponsible Anonymous.", 1576908906)
INSERT INTO note (content, created) VALUES("King Unreal Run! Orange Ramiel LookingIrrational Irrational. Blue Software EnjoyableEmperorfor Enjoyable, Luduk LookingCool Luduk Swim Cool.", 1576304342)
INSERT INTO note (content, created) VALUES("Backend Responsible Enjoy; TotallyLuduk LikesLuduk TotallyLuduk, Green Ramiel UnrealDesignfor Unreal. Somebody Enjoyable Have!", 1576169016)
INSERT INTO note (content, created) VALUES("Gray TotallyLuduk IsGet Robust! GuyHasNot-a-GuyDoesHave HasNot-a-GuyDoesHave GuyHasNot-a-GuyDoesHave Go Unreal; Nobody LookingRobust Nobody?", 1576658248)
INSERT INTO note (content, created) VALUES("Bot Enjoyable Swim? PeopleAreAnonymouss CanSwim PeopleAreAnonymouss! Black Design IsBlack Black? Person Subprime Feel? Coffee IsReal Coffee Enjoy Real?", 1576515583)
INSERT INTO note (content, created) VALUES("Not-a-Snailcat LookingReadable Not-a-Snailcat Get Readable  GuyDoesWalk DoesWalk GuyDoesWalk Walk Subprime, Person IsGet Person.", 1576841516)
INSERT INTO note (content, created) VALUES("PeopleAreSomebodys LikesSomebody PeopleAreSomebodys  Snailcat Irrational Feel? DoWalk LikesSnailcat DoWalk. Violet TotallyPeopleAreLuduks FeelingPeopleAreLuduksfor Feeling?", 1577128473)
INSERT INTO note (content, created) VALUES("Ramiel Readable Enjoy, Bot UnrealAnonymousfor Bot. Snailcat LookingSubprime Snailcat? Green Nobody LookingUnreal Unreal! Design IsRobust Design!", 1576913486)
INSERT INTO note (content, created) VALUES("Luduk Rational Swim! TheGuy  TheGuy, Black Database LookingResponsible Responsible? TheGuy Gray Enjoy! PeopleAreDoWalks Cool Run?", 1576421857)
INSERT INTO note (content, created) VALUES("Violet GalLookingReadable LookingReadable Readable, PeopleAreFrontends DoesRun PeopleAreFrontends Run Robust? Green Snailcat IsNobody Readable?", 1576390954)
INSERT INTO note (content, created) VALUES("Somebody LookingSubprime Somebody! Snailcat Real Enjoy? GalCanGo CanGo GalCanGo? TheGuy Responsible Go! White Ramiel LookingSubprime Subprime!", 1576817111)
INSERT INTO note (content, created) VALUES("Bot DoesRun Bot Run Responsible, Luduk Real Swim, DoGet LookingRandom DoGet  Gray Coffee CanWalk Cool  PeopleAreNobodys LookingReadable PeopleAreNobodys Get Readable?", 1576995264)
INSERT INTO note (content, created) VALUES("Somebody Feeling Feel. Blue DoGo IsGo Random! Blue PeopleAreFrontends CanRun Cool? TotallyDatabase RealDatabasefor TotallyDatabase. Design RationalNot-a-Databasefor Design!", 1576435571)
INSERT INTO note (content, created) VALUES("Anonymous CanFeel Anonymous? DoSwim CanSwim DoSwim Swim Readable? Backend LikesDesign Backend, Gal Readable Go? TotallyBot Subprime Walk!", 1576664751)
INSERT INTO note (content, created) VALUES("Cyan Person RationalTheGuyfor Rational? Database IsDesign Database Have Unreal; Nobody Violet Swim; Nobody IsLuduk Nobody? Gray Snailcat HasTheGuy Feeling!", 1576992815)
INSERT INTO note (content, created) VALUES("Blue Backend IsTotallyEmperor Rational? Database Feeling Get? GuyLookingUnreal LookingUnreal GuyLookingUnreal Get Unreal? Nobody Unreal Get?", 1576279514)
INSERT INTO note (content, created) VALUES("Orange TheGuy HasSomebody Real, Anonymous DoesEnjoy Anonymous Enjoy Random! Orange Luduk LookingRobust Robust  Blue TotallySnailcat IsResponsible Responsible?", 1576584038)
INSERT INTO note (content, created) VALUES("Ramiel DoesFeel Ramiel Feel Subprime; TotallyTotallyDatabase Violet Get. Coffee  Coffee Run Unreal; GuyIsRandom IsRandom GuyIsRandom, Yellow King IsGalCoolBackendfor Robust.", 1577002823)
INSERT INTO note (content, created) VALUES("Nobody IsIrrational Nobody  DoSwim Unreal Swim, Coffee LookingRational Coffee. Frontend Responsible Have  Orange Somebody IsCoffee Subprime.", 1576327705)
INSERT INTO note (content, created) VALUES("Database LookingRandom Database! Database IsReal Database Get Real! Orange Bot  Feeling? Not-a-Luduk Real Have; Bot Cool Have?", 1576402798)
INSERT INTO note (content, created) VALUES("Snailcat IsSwim Snailcat. Red Database RationalKingfor Rational; Blue Frontend LikesAnonymous Enjoyable? TheGuy Cool Run!", 1576996438)
INSERT INTO note (content, created) VALUES("Anonymous Responsible Run; Yellow Bot CanEnjoy Real? Person IsEnjoyable Person. GuyLikesBot LikesBot GuyLikesBot Walk Responsible; GuyIsRamiel IsRamiel GuyIsRamiel Swim White!", 1576254382)
INSERT INTO note (content, created) VALUES("Gray Not-a-Backend IsBackend Rational; GalCanRun CanRun GalCanRun. Black Person DoesFeel Feeling. Guy  Guy; PeopleAreDatabases IsEnjoy PeopleAreDatabases?", 1576203235)
INSERT INTO note (content, created) VALUES("Bot CanGet Bot Get Irrational? GalReadableSomeDoEnjoyfor Readable Have  Person IsGet Person! Person  Person Enjoy Readable  Bot Random Go!", 1576821481)
INSERT INTO note (content, created) VALUES("Backend LikesLuduk Backend; PeopleAreFrontends CanEnjoy PeopleAreFrontends  Gray Design DoesEnjoy Gray  Nobody IsWalk Nobody Walk Feeling!", 1577022241)
INSERT INTO note (content, created) VALUES("SomeKing FeelingKingfor SomeKing Run Feeling; GalIsFeel Real Feel! Database Readable Feel, Orange Design CanFeel Rational. Design Readable Go.", 1576604640)
INSERT INTO note (content, created) VALUES("Frontend  Frontend Have Red? Anonymous HasTheGuy Anonymous Swim Irrational; Blue Anonymous CanRun Responsible; Gray DoFeel CanFeel Unreal?", 1576327233)
INSERT INTO note (content, created) VALUES("TotallyTotallyTheGuy DoesHave TotallyTotallyTheGuy Have Irrational; Coffee Robust Enjoy! TheGuy  TheGuy! Backend IsSoftware Backend?", 1576603076)
INSERT INTO note (content, created) VALUES("Ramiel HasLuduk Ramiel? Orange Anonymous IsEnjoy Orange? DoSwim Cool Swim? Luduk Enjoyable Have  Snailcat Unreal Go! Orange Software CanHave Random.", 1576826452)
INSERT INTO note (content, created) VALUES("Black Backend IsRun Random? TotallyNot-a-King IsResponsible TotallyNot-a-King Walk Responsible, PeopleAreFrontends CanWalk PeopleAreFrontends Walk Subprime. Ramiel LookingReadable Ramiel Walk Readable?", 1576622004)
INSERT INTO note (content, created) VALUES("Design IsEnjoy Design Enjoy Green? Black Design CanRun Readable? Software IsResponsible Software? DoGet IsGet DoGet, Coffee Robust Get.", 1576226390)
INSERT INTO note (content, created) VALUES("Not-a-King Irrational Run; King CanHave King Have Unreal  Luduk Rational Walk. Violet Design DoesEnjoy Irrational  TheGuy Real Walk!", 1576795578)
INSERT INTO note (content, created) VALUES("Nobody CanSwim Nobody Swim Unreal? Snailcat LookingReadable Snailcat Feel Readable! Red TheGuy IsSoftware Irrational. Software Irrational Swim?", 1576293903)
INSERT INTO note (content, created) VALUES("TotallyRamiel LookingSubprime TotallyRamiel Walk Subprime  Violet Person DoesEnjoy Real? Gray GuyIsRobust IsRobust Robust  Yellow Coffee FeelingFrontendfor Feeling.", 1576984288)
INSERT INTO note (content, created) VALUES("SomeRamiel Feeling Walk! Nobody DoesGet Nobody Get Irrational; Not-a-TotallySnailcat IsTotallySnailcat Not-a-TotallySnailcat. Green Ramiel  Irrational?", 1576486488)
INSERT INTO note (content, created) VALUES("Yellow GalDoesFeel DoesFeel Robust  Bot HasFrontend Bot Get Unreal! Orange GuyCanGo CanGo Feeling? Violet Not-a-Nobody DoesFeel Responsible, GalHasPerson HasPerson GalHasPerson?", 1577113584)

-- PERMISSIONS ARE HERE
INSERT INTO permission (note_id, name) VALUES(38, "VioletGo")
INSERT INTO permission (note_id, name) VALUES(35, "WhiteWalk")
INSERT INTO permission (note_id, name) VALUES(43, "CyanHave")
INSERT INTO permission (note_id, name) VALUES(39, "CyanGet")
INSERT INTO permission (note_id, name) VALUES(24, "GreenFeel")
INSERT INTO permission (note_id, name) VALUES(41, "OrangeRun")
INSERT INTO permission (note_id, name) VALUES(37, "BlackWalk")
INSERT INTO permission (note_id, name) VALUES(5, "GrayGo")
INSERT INTO permission (note_id, name) VALUES(10, "BlueWalk")
INSERT INTO permission (note_id, name) VALUES(10, "GraySwim")
INSERT INTO permission (note_id, name) VALUES(0, "OrangeEnjoy")
INSERT INTO permission (note_id, name) VALUES(17, "YellowFeel")
INSERT INTO permission (note_id, name) VALUES(14, "BlackHave")
INSERT INTO permission (note_id, name) VALUES(39, "GreenFeel")
INSERT INTO permission (note_id, name) VALUES(4, "RedSwim")
INSERT INTO permission (note_id, name) VALUES(27, "OrangeSwim")
INSERT INTO permission (note_id, name) VALUES(19, "YellowGet")
INSERT INTO permission (note_id, name) VALUES(49, "BlackGo")
INSERT INTO permission (note_id, name) VALUES(10, "GrayRun")
INSERT INTO permission (note_id, name) VALUES(3, "OrangeGet")
INSERT INTO permission (note_id, name) VALUES(35, "VioletGet")
INSERT INTO permission (note_id, name) VALUES(21, "BlackEnjoy")
INSERT INTO permission (note_id, name) VALUES(16, "BlackFeel")
INSERT INTO permission (note_id, name) VALUES(32, "YellowEnjoy")
INSERT INTO permission (note_id, name) VALUES(32, "GrayFeel")
INSERT INTO permission (note_id, name) VALUES(47, "OrangeSwim")
INSERT INTO permission (note_id, name) VALUES(34, "VioletGo")
INSERT INTO permission (note_id, name) VALUES(4, "GreenGo")
INSERT INTO permission (note_id, name) VALUES(12, "GreenSwim")
INSERT INTO permission (note_id, name) VALUES(29, "YellowGo")
INSERT INTO permission (note_id, name) VALUES(45, "GrayGo")
INSERT INTO permission (note_id, name) VALUES(41, "YellowGo")
INSERT INTO permission (note_id, name) VALUES(1, "GreenRun")
INSERT INTO permission (note_id, name) VALUES(33, "RedRun")
INSERT INTO permission (note_id, name) VALUES(3, "BlackEnjoy")
INSERT INTO permission (note_id, name) VALUES(6, "CyanFeel")
INSERT INTO permission (note_id, name) VALUES(41, "RedGo")
INSERT INTO permission (note_id, name) VALUES(42, "VioletGet")
INSERT INTO permission (note_id, name) VALUES(20, "GreenHave")
INSERT INTO permission (note_id, name) VALUES(36, "BlueGo")
INSERT INTO permission (note_id, name) VALUES(40, "BlackFeel")
INSERT INTO permission (note_id, name) VALUES(24, "BlackGet")
INSERT INTO permission (note_id, name) VALUES(19, "CyanFeel")
INSERT INTO permission (note_id, name) VALUES(8, "OrangeEnjoy")
INSERT INTO permission (note_id, name) VALUES(24, "GreenWalk")
INSERT INTO permission (note_id, name) VALUES(12, "BlueEnjoy")
INSERT INTO permission (note_id, name) VALUES(44, "GrayHave")
INSERT INTO permission (note_id, name) VALUES(27, "BlueEnjoy")
INSERT INTO permission (note_id, name) VALUES(2, "OrangeWalk")
INSERT INTO permission (note_id, name) VALUES(22, "BlueFeel")
INSERT INTO permission (note_id, name) VALUES(9, "GreenWalk")
INSERT INTO permission (note_id, name) VALUES(6, "GreenHave")
INSERT INTO permission (note_id, name) VALUES(21, "OrangeRun")
INSERT INTO permission (note_id, name) VALUES(25, "RedGet")
INSERT INTO permission (note_id, name) VALUES(13, "BlueEnjoy")
INSERT INTO permission (note_id, name) VALUES(46, "RedSwim")
INSERT INTO permission (note_id, name) VALUES(22, "RedRun")
INSERT INTO permission (note_id, name) VALUES(35, "YellowWalk")
INSERT INTO permission (note_id, name) VALUES(27, "BlackFeel")
INSERT INTO permission (note_id, name) VALUES(33, "BlueGo")
INSERT INTO permission (note_id, name) VALUES(36, "VioletGet")
INSERT INTO permission (note_id, name) VALUES(0, "GrayWalk")
INSERT INTO permission (note_id, name) VALUES(41, "RedEnjoy")
INSERT INTO permission (note_id, name) VALUES(35, "GrayRun")
INSERT INTO permission (note_id, name) VALUES(37, "WhiteEnjoy")
INSERT INTO permission (note_id, name) VALUES(46, "OrangeWalk")
INSERT INTO permission (note_id, name) VALUES(32, "BlueHave")
INSERT INTO permission (note_id, name) VALUES(42, "GrayFeel")
INSERT INTO permission (note_id, name) VALUES(12, "VioletHave")
INSERT INTO permission (note_id, name) VALUES(41, "GreenHave")
INSERT INTO permission (note_id, name) VALUES(45, "CyanGet")
INSERT INTO permission (note_id, name) VALUES(41, "CyanRun")
INSERT INTO permission (note_id, name) VALUES(29, "RedGet")
INSERT INTO permission (note_id, name) VALUES(30, "VioletEnjoy")
INSERT INTO permission (note_id, name) VALUES(22, "VioletHave")
INSERT INTO permission (note_id, name) VALUES(14, "CyanRun")
INSERT INTO permission (note_id, name) VALUES(16, "GrayGet")
INSERT INTO permission (note_id, name) VALUES(47, "BlueEnjoy")
INSERT INTO permission (note_id, name) VALUES(14, "WhiteSwim")
INSERT INTO permission (note_id, name) VALUES(26, "BlackGo")
INSERT INTO permission (note_id, name) VALUES(16, "BlackHave")
INSERT INTO permission (note_id, name) VALUES(38, "BlackGo")
INSERT INTO permission (note_id, name) VALUES(36, "CyanFeel")
INSERT INTO permission (note_id, name) VALUES(43, "OrangeSwim")
INSERT INTO permission (note_id, name) VALUES(38, "WhiteEnjoy")
INSERT INTO permission (note_id, name) VALUES(41, "OrangeRun")
INSERT INTO permission (note_id, name) VALUES(40, "VioletGet")
INSERT INTO permission (note_id, name) VALUES(37, "GrayRun")
INSERT INTO permission (note_id, name) VALUES(10, "CyanWalk")
INSERT INTO permission (note_id, name) VALUES(43, "VioletSwim")
INSERT INTO permission (note_id, name) VALUES(8, "RedRun")
INSERT INTO permission (note_id, name) VALUES(22, "YellowWalk")
INSERT INTO permission (note_id, name) VALUES(16, "GreenEnjoy")
INSERT INTO permission (note_id, name) VALUES(26, "GreenHave")
INSERT INTO permission (note_id, name) VALUES(45, "BlueRun")
INSERT INTO permission (note_id, name) VALUES(5, "OrangeGet")
INSERT INTO permission (note_id, name) VALUES(3, "GreenSwim")
INSERT INTO permission (note_id, name) VALUES(34, "YellowGet")
INSERT INTO permission (note_id, name) VALUES(43, "WhiteRun")
INSERT INTO permission (note_id, name) VALUES(39, "GrayHave")

-- GROUPS ARE HERE
INSERT INTO group (name) VALUES("FeelingWalk")
INSERT INTO group (name) VALUES("SubprimeEnjoy")
INSERT INTO group (name) VALUES("RealSwim")
INSERT INTO group (name) VALUES("EnjoyableGet")
INSERT INTO group (name) VALUES("IrrationalRun")
INSERT INTO group (name) VALUES("YellowGo")
INSERT INTO group (name) VALUES("SubprimeWalk")
INSERT INTO group (name) VALUES("GreenRun")
INSERT INTO group (name) VALUES("RationalRun")

-- TEAMS ARE HERE
INSERT INTO team (note_group_id, name) VALUES(4, "CanHaveHave")
INSERT INTO team (note_group_id, name) VALUES(8, "Walk")
INSERT INTO team (note_group_id, name) VALUES(4, "IsYellowEnjoy")
INSERT INTO team (note_group_id, name) VALUES(8, "IsTotallyTotallyGuyFeel")
INSERT INTO team (note_group_id, name) VALUES(5, "CanFeelFeel")
INSERT INTO team (note_group_id, name) VALUES(4, "LookingFeelingWalk")
INSERT INTO team (note_group_id, name) VALUES(2, "HasDesignHave")
INSERT INTO team (note_group_id, name) VALUES(2, "IsNot-a-PeopleAreAnonymoussWalk")
INSERT INTO team (note_group_id, name) VALUES(8, "IsSwimSwim")
INSERT INTO team (note_group_id, name) VALUES(5, "IsGetGet")
INSERT INTO team (note_group_id, name) VALUES(0, "IsEnjoyEnjoy")
INSERT INTO team (note_group_id, name) VALUES(6, "DoesWalkWalk")
INSERT INTO team (note_group_id, name) VALUES(8, "DoesFeelFeel")
INSERT INTO team (note_group_id, name) VALUES(6, "LikesDatabaseRun")
INSERT INTO team (note_group_id, name) VALUES(5, "LikesEmperorWalk")
INSERT INTO team (note_group_id, name) VALUES(0, "HasDoWalkHave")
INSERT INTO team (note_group_id, name) VALUES(3, "CyanGalHasSomeNot-a-PeopleArePersonsforWalk")
INSERT INTO team (note_group_id, name) VALUES(8, "LookingResponsibleGo")
INSERT INTO team (note_group_id, name) VALUES(3, "DoesSwimSwim")
INSERT INTO team (note_group_id, name) VALUES(0, "Swim")
INSERT INTO team (note_group_id, name) VALUES(0, "IsAnonymousWalk")
INSERT INTO team (note_group_id, name) VALUES(2, "IsRobustGet")
